# Generated by Django 4.1.dev20211117113125 on 2021-11-24 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('upload_file', models.FileField(upload_to='media/')),
                ('language', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TextFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_file', models.TextField(max_length=4000)),
                ('audiofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcripen.audiofile')),
            ],
        ),
    ]
