# Generated by Django 4.1.dev20211117113125 on 2021-11-24 23:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transcripen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Added Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audiofile',
            name='name',
            field=models.CharField(default='Sans titre', max_length=200),
        ),
        migrations.AddField(
            model_name='textfile',
            name='name',
            field=models.CharField(default='Sans-titre', max_length=200),
            preserve_default=False,
        ),
    ]
